/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Element, } from "@stencil/core";
export namespace Components {
    interface FortysevenRobeen {
        "dataUrl": string;
    }
    interface RobeenTooltip {
        "hide": () => Promise<void>;
        "show": (index: number, data: any, positions: number[]) => Promise<void>;
        "tooltip": (tooltip: Element) => Promise<void>;
    }
}
declare global {
    interface HTMLFortysevenRobeenElement extends Components.FortysevenRobeen, HTMLStencilElement {
    }
    var HTMLFortysevenRobeenElement: {
        prototype: HTMLFortysevenRobeenElement;
        new (): HTMLFortysevenRobeenElement;
    };
    interface HTMLRobeenTooltipElement extends Components.RobeenTooltip, HTMLStencilElement {
    }
    var HTMLRobeenTooltipElement: {
        prototype: HTMLRobeenTooltipElement;
        new (): HTMLRobeenTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "fortyseven-robeen": HTMLFortysevenRobeenElement;
        "robeen-tooltip": HTMLRobeenTooltipElement;
    }
}
declare namespace LocalJSX {
    interface FortysevenRobeen {
        "dataUrl"?: string;
    }
    interface RobeenTooltip {
    }
    interface IntrinsicElements {
        "fortyseven-robeen": FortysevenRobeen;
        "robeen-tooltip": RobeenTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fortyseven-robeen": LocalJSX.FortysevenRobeen & JSXBase.HTMLAttributes<HTMLFortysevenRobeenElement>;
            "robeen-tooltip": LocalJSX.RobeenTooltip & JSXBase.HTMLAttributes<HTMLRobeenTooltipElement>;
        }
    }
}
