/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  GraphData,
} from '@app/types/types';
import {
  Element,
} from '@stencil/core';


export namespace Components {

  interface HorizontalBarChart {
    'dataUrl': string;
    'graphData': GraphData<number[]>;
    'updateGraphData': (graphData: any) => void;
  }
  interface HorizontalBarChartAttributes extends StencilHTMLAttributes {
    'dataUrl'?: string;
    'graphData'?: GraphData<number[]>;
  }

  interface TooltipChart {
    'align': string;
    'hide': () => void;
    'show': (index: number, data: any, positions: number[]) => void;
    'tooltip': (tooltip: Element) => void;
  }
  interface TooltipChartAttributes extends StencilHTMLAttributes {
    'align'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'HorizontalBarChart': Components.HorizontalBarChart;
    'TooltipChart': Components.TooltipChart;
  }

  interface StencilIntrinsicElements {
    'horizontal-bar-chart': Components.HorizontalBarChartAttributes;
    'tooltip-chart': Components.TooltipChartAttributes;
  }


  interface HTMLHorizontalBarChartElement extends Components.HorizontalBarChart, HTMLStencilElement {}
  var HTMLHorizontalBarChartElement: {
    prototype: HTMLHorizontalBarChartElement;
    new (): HTMLHorizontalBarChartElement;
  };

  interface HTMLTooltipChartElement extends Components.TooltipChart, HTMLStencilElement {}
  var HTMLTooltipChartElement: {
    prototype: HTMLTooltipChartElement;
    new (): HTMLTooltipChartElement;
  };

  interface HTMLElementTagNameMap {
    'horizontal-bar-chart': HTMLHorizontalBarChartElement
    'tooltip-chart': HTMLTooltipChartElement
  }

  interface ElementTagNameMap {
    'horizontal-bar-chart': HTMLHorizontalBarChartElement;
    'tooltip-chart': HTMLTooltipChartElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
