/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Element,
} from '@stencil/core';


export namespace Components {

  interface FortysevenRobeen {
    'dataUrl': string;
  }
  interface FortysevenRobeenAttributes extends StencilHTMLAttributes {
    'dataUrl'?: string;
  }

  interface RobeenTooltip {
    'hide': () => void;
    'show': (index: number, data: any, positions: number[]) => void;
    'tooltip': (tooltip: Element) => void;
  }
  interface RobeenTooltipAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'FortysevenRobeen': Components.FortysevenRobeen;
    'RobeenTooltip': Components.RobeenTooltip;
  }

  interface StencilIntrinsicElements {
    'fortyseven-robeen': Components.FortysevenRobeenAttributes;
    'robeen-tooltip': Components.RobeenTooltipAttributes;
  }


  interface HTMLFortysevenRobeenElement extends Components.FortysevenRobeen, HTMLStencilElement {}
  var HTMLFortysevenRobeenElement: {
    prototype: HTMLFortysevenRobeenElement;
    new (): HTMLFortysevenRobeenElement;
  };

  interface HTMLRobeenTooltipElement extends Components.RobeenTooltip, HTMLStencilElement {}
  var HTMLRobeenTooltipElement: {
    prototype: HTMLRobeenTooltipElement;
    new (): HTMLRobeenTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'fortyseven-robeen': HTMLFortysevenRobeenElement
    'robeen-tooltip': HTMLRobeenTooltipElement
  }

  interface ElementTagNameMap {
    'fortyseven-robeen': HTMLFortysevenRobeenElement;
    'robeen-tooltip': HTMLRobeenTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
